export const newArrivalProducts = [
  {
    id: 1,
    title: "Activewear",
    slug: "activewear-1",
    description: "Comfortable and stylish activewear for all-day wear",
    price: 50,
    image: "/img-1.jpg",
    category: "Sportswear",
    type: "new",
  },
  {
    id: 3,
    title: "Sneakers",
    slug: "sneakers-3",
    description: "Trendy casual shoes for everyday style",
    price: 90,
    image: "/img-2.jpg",
    category: "Footwear",
    type: "new",
  },
  {
    id: 7,
    title: "Activewear",
    slug: "activewear-7",
    description: "Comfortable and stylish activewear for all-day wear",
    price: 50,
    image: "/img-3.jpg",
    category: "Sportswear",
    type: "new",
  },
  {
    id: 8,
    title: "Sneakers",
    slug: "sneakers-8",
    description: "Trendy casual shoes for everyday style",
    price: 90,
    image: "/img-4.jpg",
    category: "Footwear",
    type: "new",
  },
];

export const mostPopularProducts = [
  {
    id: 2,
    title: "Formal Shirt",
    slug: "formal-shirt-2",
    description: "Perfect for office wear",
    price: 70,
    category: "Formal Wear",
    type: "popular",
    colorImages: {
      Green: "/img-a-green.jpg",
      Black: "/img-a-black.jpg",
      Red: "/img-a-red.jpg",
      White: "/img-a-white.jpg",
    },
    colorPrices: {
      Green: 70,
      Black: 72,
      Red: 88,
      White: 75,
    },
  },
  {
    id: 4,
    title: "Jacket",
    slug: "jacket-4",
    description: "Best seller winter wear for warmth and style",
    price: 120,
    category: "Outerwear",
    type: "popular",
    colorImages: {
      Black: "/img-b-black.jpg",
      Green: "/img-b-green.jpg",
      Red: "/img-b-red.jpg",
    },
    colorPrices: {
      Black: 120,
      Green: 125,
      Red: 122,
    },
  },
  {
    id: 5,
    title: "Jacket",
    slug: "jacket-5",
    description: "Best seller winter wear for warmth and style",
    price: 120,
    category: "Outerwear",
    type: "popular",
    colorImages: {
      Black: "/img-c-black.jpg",
      Green: "/img-c-green.jpg",
      Red: "/img-c-red.jpg",
      White: "/img-c-white.jpg",
    },
    colorPrices: {
      Black: 120,
      Green: 125,
      Red: 122,
      White: 887,
    },
  },
  {
    id: 6,
    title: "Jacket",
    slug: "jacket-6",
    description: "Best seller winter wear for warmth and style",
    price: 120,
    category: "Outerwear",
    type: "popular",
    colorImages: {
      Black: "/img-d-black.jpg",
      Green: "/img-d-green.jpg",
      Red: "/img-d-red.jpg",
      White: "/img-d-white.jpg",
    },
    colorPrices: {
      Black: 120,
      Green: 125,
      Red: 122,
      White: 56,
    },
  },
];
